version: '3.9'
services:
  backend:
    build: ./apps/backend
    env_file:
      - ./apps/backend/.env
    ports:
      - "3005:3001"
    networks: [appnet]
  frontend:
    build: ./apps/frontend
    environment:
      - VITE_API_BASE_URL=http://backend:3001
    ports:
      - "6789:80"
    networks: [appnet]
volumes:
  pgdata:
networks:
  appnet:
