services:
  bonarr:
    image: pajammies/bonarr:latest
    container_name: bonarr
    environment:
      - NODE_ENV=production
      - PORT=3005
      # When frontend is served by the same backend, same-origin requests do not require CORS,
      # but leaving this set to the public origin is harmless.
      - CORS_ORIGIN=http://localhost:3005
    ports:
      - "3005:3005"
    volumes:
      # Mount Real Debrid library
      - /docker/media_stack/media:/media
      # Mount symlink staging directory
      #- /path/to/local/symlinks:/mnt/bonarr/symlinks
      # Optional: Mount configuration file
      - /docker/media_stack/bonarr/config.json:/app/bonarr-config.json
    devices:
      # Optional: If you need to use rclone with system devices
      - /dev/fuse:/dev/fuse
    privileged: true  # Required for rclone mounting
